### ISSUE TITLE
plotting of state tracking for car is upside down 

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#82]
In teh dynamic systems class, can you work on plotting the state probabilities as positive values?

**Comment by wouterwln** [comment]
I already spent quite some time on this when I first made this plot. The problem is that the state probabilities are plotted as positive values, but the axis is flipped for some reason. Things I tried are:
- Manually inverting the axes.
- Plotting the PDF's BEFORE plotting the image (as to maybe fix axis layout)
- Plotting the image upside down and flipping the entire plot so it is right side up
- Inverting the axes and loading the image upside down
I'm at a loss for how to fix this. @wmkouw do you maybe have an idea I could try out? I'm not that experienced with Plots. If all else fails I'll just open an issue in the Plots repo. Will do that later this week after I take another crack at it.
