### ISSUE TITLE
update SW instructions to run a notebook

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#90]
At the BMLIP homepage the following SW instructions are given:

```
- Please install Miscrosoft's VS code editor and add the Jupyter notebook extension.
- Please install Julia version 1.9 on your machine and then add the Julia extension in VS code.
```

I have a new machine and I did this. I still could not run the notebooks for my lessons in the VS code editor. I had to add the `IJulia` package to Julia, and then run `Pkg.build("IJulia")` in the Julia prompt, otherwise Jupyter cannot find the Julia kernel to run the notebook. This is probably obvious to you, but technically the instructions above are insufficient to run the notebooks in VS code. This will lead to frustration. 

Please update the software instructions on the homepage to the **exact preparations** that a user needs (from scratch) in order to run the notebooks in the VS code editor.

**Comment by wmkouw** [comment]
When I tested it in a clean environment last year, VSCode downloaded IJulia automatically when I wanted to start a julia kernel in Jupyter. But I will check the procedure again and make sure the instructions are exact.

**Comment by wmkouw** [comment]
I extended the software installation instructions, see https://github.com/biaslab/biaslab-hugo/commit/0262c47fcf664be1757a0792eaac47b3dafc6de3. I tested them with an Ubuntu distro and a Windows 10 VM. I can't start a Mac OS VM since I don't have a product key. But I presume the Linux instructions will work for Mac as well.
